PATH_PRJ_ROOT:=$(if $(PATH_PRJ_ROOT), $(PATH_PRJ_ROOT), .)

INC=-I include/ 

SRC_DIR=./src/
OBJS_DIR=./src/
BIN_DIR=./lib/

BITS=64
LIB_TARGET=libconfig_64.a

include $(PATH_PRJ_ROOT)/makeinclude/makefile.libcomm
